Sprint 6
harshp24asopalav/MedMatch pull request #8
Opened 2024-07-25 16:43 UTC by harshp24asopalav

This sprint covers the development of all use cases along with their frontend app.

2024-07-30 16:12 UTC, enriqueespinosa commented on diabetes.py
> +            print("Training new model...")
Nice, clean code!

2024-07-30 16:13 UTC, enriqueespinosa commented on diabetes.py
> +        df = pd.read_csv('./data-collection/Diabetes/diabetes_prediction_dataset.csv')
This is not a secret, but it would be better not to hardcode it anymore.

2024-07-30 16:35 UTC, enriqueespinosa requested changes
Docker secrets are not implemented.
I cannot find logger and log statements.
I am holding on the approval until I get clarification.

2024-07-30 18:01 UTC, enriqueespinosa commented
I just received a new email with the same pull request. 
Nothing that I can see has changed in the past two hours since I last checked the code.
The expectation is that you develop and submit Docker Secrets and Log management.

2024-08-07 10:45 UTC, ProfEspinosaAIML approved these changes
Approved

2024-08-14 13:33 UTC, merged